config/routes.rb
Therearenews::Application.routes.draw do |map|
  resources :feeds

  devise_for :users

  resources :user
  resources :feeds
  root :to => "welcome#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :update, :destroy], User do |user_access|
      user && user_access.id == user.id
    end
    can [:create], User

    can [:read, :update, :destroy], Feed do | feed|
      feed.user_id == user.id
    end
    can :create, Feed
  end

end

app/models/feed.rb
class Feed
  include Mongoid::Document

  field :url, :type => String
  field :login_to_push, :type => String

  belongs_to_related :user

  before_save :subscribe_feed

  def subscribe_feed
    Therearenews::Application::SUBSCRIBE_CHANNEL.push(url)
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  field :login, :type => String

  has_many_related :feeds

  validates_presence_of :login
  validates_uniqueness_of :login

  index :login, :unique => true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :rememberable, :trackable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/feeds_controller.rb
class FeedsController < InheritedResources::Base

  actions :new, :create, :edit, :update, :destroy

  load_and_authorize_resource

  def create
    @feed = Feed.new(params[:feed])
    @feed.user = current_user
    create! do |format|
      format.html { redirect_to user_url(current_user) }
    end
  end

  def destroy
    destroy! do |format|
      format.html { redirect_to user_url(current_user) }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  load_and_authorize_resource

  def create
    create! do |format|
      format.html {
        sign_in @user
        redirect_to user_url(@user)
      }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/new.html.haml
%h1 Add feed

= simple_form_for @feed do |f|
  = f.input :url
  = f.input :login_to_push
  = f.button :submit

= link_to 'Back', user_path(current_user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      There are news ?
    = csrf_meta_tag
  %body
    #userbox
      %ul
        - if user_signed_in?
          %li
            Welcome abord
            = current_user.login
          %li= link_to(t('views.layout.logout'), destroy_user_session_url)
        - else
          %li=link_to(t('views.layout.login'), new_user_session_url)
          %li=link_to(t('views.layout.register'), new_user_url)
    #flash
      %p.notice= notice
      %p.alert= alert

    = yield

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :login
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Back', @user

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Github login
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.github_login
      - if can?(:read, user)
        %td= link_to 'Show', user
      - if can?(:update, user)
        %td= link_to 'Edit', edit_user_path(user)
      - if can?(:destroy, user)
        %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

- if can?(:create, User)
  = link_to 'New user', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'


= link_to 'Back', users_path

app/views/users/show.html.haml
%dl
  %dt Name:
  %dd= @user.login

%h1 All feeds manage

= link_to 'Create feed', new_feed_path
%table
  %thead
    %tr
      %th Feed
      %th login_to_push
  %tbody
    - @user.feeds.each do |feed|
      %tr
        %td= feed.url
        %td= feed.login_to_push
        %td= button_to "Delete", feed_url(feed), :confirm => "Are you sure?", :method => :delete

= link_to 'Edit', edit_user_path(@user)

app/views/welcome/index.html.haml
#content
  = t('views.welcome.index.hello')